//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.DataAccess.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Activities = new HashSet<Activity>();
            this.Hydrations = new HashSet<Hydration>();
            this.Meals = new HashSet<Meal>();
        }
    
        public int PersonId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Hydration> Hydrations { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
